name: Build vuepress website
permissions:
  contents: write
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install and Build
      run: |
        npm ci
        npm run build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .vuepress/dist
        clean-exclude: |
          CNAME

